name: first workflow

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    name: job1
    runs-on: ubuntu-latest
    # Checkout source code 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: run a custom command
        run: echo "Hello world"
